name: Users CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build and push users Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        cd users
        docker build -t sivakumar2905/users:latest .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push sivakumar2905/users:latest

    - name: Pull Docker image
      run: sudo docker pull sivakumar2905/users:latest

    - name: Delete Old docker container
      run: sudo docker rm -f users-container || true

    - name: Run Docker Container
      run: sudo docker run -d -p 4001:4001 --name users-container sivakumar2905/users:latest
